### PR TITLE
Bbolker fixes

### PR DESCRIPTION
**Pull request by bbolker**
This is a big pull request. Most of it is small stylistic/grammar stuff. There is one minor, possibly controversial commit and one major, possibly controversial commit ...

- minor: commit eb4d020 removes the shortcut of putting functions without parentheses into piped workflows. This is really a stylistic question. The arguments in favour are: (1) it saves a couple of keystrokes and a couple of characters in the pipeline; (2) learners may eventually see it in other people's code. The argument against is that it's a weird little bit of syntactic sugar that adds *more* cognitive load beyond the basic "functions in pipelines get their first argument filled in automatically" concept.

- major commit 7bf9f3f uses a modified version of the data set to show gathering before spreading. My argument is that this is (in my experience) the #1 use case for `tidyr`.

Looking forward to comments.

### CODE REVIEW

**Comment by bbolker** [comment]
PS - the modified data set used for the gathering example is generated automatically, but will need to be put somewhere sensible for downloading by learners. Also, I stole a figure from the software carpentry tidy lesson 14 ...)

**Comment by aurielfournier** [comment]
Hi @bbolker, thanks for putting in all this time, it is appreciated. Would it be possible for you to submit them as 3 separate pull requests? 

It would be great to have 1 for the minor typos, 1 for `eb4d020` and 1 for ` 7bf9f3f` 

That way we can give you appropriate feedback, and merge in smaller chunks as we go over them.

**Comment by bbolker** [comment]
of course.

**Comment by bbolker** [comment]
done, closing.

**Pull request closed without merging**
