### PR TITLE
Fix link to LICENSE.Rmd

### LINKED ISSUE #205: Update CONTRIBUTING
As part of the release process, we need to make sure that CONTRIBUTING.md is up to date.

### PR DESCRIPTION
**Pull request by ashander**
together with fixes by @ha0ye in 61e2b306 closes #205

### CODE REVIEW

**Comment by fmichonneau** [comment]
actually can you link to LICENSE.html
Thanks!

**Comment by ashander** [comment]
Wait, so should I link to http://www.datacarpentry.org/R-ecology-lesson/LICENSE.html? 

just dropping (LICENSE.html) in the md file will link to the raw-ish html on github https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/LICENSE.html

**Comment by ashander** [comment]
(You can see that behavior live at https://github.com/ashander/R-ecology-lesson/blob/gh-pages/CONTRIBUTING.md )

**Comment by fmichonneau** [comment]
yes, I agree, linking to the Rmd makes the most sense. Thanks!

**Pull request merged**
