### PR TITLE
Add template

### PR DESCRIPTION
**Pull request by ErinBecker**
@tracykteal

### CODE REVIEW

**Comment by fmichonneau** [comment]
LGTM. I'm wondering if we should add a sentence that would speak to people who are opening an issue/PR outside of instructor checkout. We routinely have contributors who are fixing typos while browsing the content for instance, and they might be put off by seeing this message.

**Comment by ErinBecker** [comment]
@fmichonneau Not opposed in theory to changes, except that the same wording has been merged into a few other repos now and I think it would be good to have consistent templating language throughout if possible.

To my mind, the second para is general (all contributors) and the first directed toward people submitting contributions for instructor training.

**Comment by fmichonneau** [comment]
OK, let's leave as it is for now, and if there is confusion we can revisit the wording. Thanks!

**Comment by ErinBecker** [comment]
@fmichonneau Thanks!

**Pull request merged**
