### PR TITLE
include script file saving - typo fix attempt 1

### PR DESCRIPTION
**Pull request by bridgeta**
...

### CODE REVIEW

**Comment by bridgeta** [comment]
Still figuring out Github
this was in error

**Comment by fmichonneau** [comment]
@bridgeta thanks for incorporating the suggested changes. Before I merge this, there still the issue of the shortcut for saving. The text says "Shift+S" but I think it's "Ctrl+S" (and "⌘ + S" for macOS). Which operating system do you use and do you use "Shift"?

**Comment by bridgeta** [comment]
I see now. I'll make the change.

**Comment by fmichonneau** [comment]
replaced by #625

**Pull request closed without merging**
