### PR TITLE
code demos how to install lubridate package

### PR DESCRIPTION
**Pull request by kelshmo**
This lesson assumes the student knows how to install packages. I made a small change so the code demos how to both load and install packages.

### CODE REVIEW

**Comment by fmichonneau** [comment]
hello @kelshmo! Thanks for your suggestion! The lubridate package gets installed when we install the tidyverse package. We give the installation instructions in the last paragraph here: https://datacarpentry.org/R-ecology-lesson/#setup_instructions

The paragraph just above your edit explains why we don't need to install lubridate. Would you have a suggestion to make this clearer?

**Comment by kelshmo** [comment]
hi @fmichonneau. You are correct! I did not notice instructions to install under [Setup](https://datacarpentry.org/R-ecology-lesson/#setup_instructions). 

It might make sense to explicitly note `install.packages` again since this is likely the users first time with R though I updated to the appropriate package `tidyverse`.

**Comment by katrinleinweber** [comment]
That install is already instructed on the main page: https://github.com/datacarpentry/R-ecology-lesson/blob/2119e487b3284aab27cff51893cd604d1363bdfd/index.Rmd#L141-L149

How about we rather aggregate [all other installs that are scattered over the different `.Rmd` files](https://github.com/datacarpentry/R-ecology-lesson/search?l=RMarkdown&q=%22install.packages%22) there?

**Comment by mondorescue** [comment]
I'm going to close this PR as instructions on installing the tidyverse package is present, but the possibly of reintroducing the steps to install the package in appropriate areas for will be taken into consideration for clarity. Thank you for your contribution.

**Pull request closed without merging**
