### PR TITLE
Count for combination of factor in the dplyr lesson

### PR DESCRIPTION
**Pull request by gederajeg**
I add two code-chunks in the "03-dplyr.Rmd" lesson in the **counting** section.
The first chunk shows how to generate **co-occurrence** count between _a set of factors_ (i.e. `sex` and `species`) using `dplyr::count()`, complementing the example of `dplyr::count()` for a single factor (i.e. `sex`). 
The second chunk shows the use of `dplyr::arrange()` to sort the co-occurrence count given _a set of criteria_, complementing the previous example for `dplyr::arrange()` before the **counting** section.

### CODE REVIEW

**Comment by fmichonneau** [comment]
This looks good to me. Could another maintainer also review and merge?

**Comment by aurielfournier** [comment]
Looks good to me as well. Thanks @gederajeg !

**Comment by orchid00** [comment]
Hi, I'm not a maintainer, but I'm going to teach the lesson, so I want to give my 2 cents.

1)Thinking about cognitive load, would rather not add more.

2) In case it is added, I suggest to add an optional tag - especially for new instructors who follow the notes line by line. 
Also please don't introduce in the exercise the use of n() as it hasn't been taught before. 
Slight grammatical corrections will be needed in the text too.

**Comment by aurielfournier** [comment]
Thanks for the input @orchid00 , would you be up for submitting a PR with those grammatical corrections?

**Pull request merged**
