### PR TITLE
formatting fixes and minor name fixes

### PR DESCRIPTION
**Pull request by ha0ye**
(see commit info for details, but addressing  ##182 and some other minor things I noticed)

### CODE REVIEW

**Comment by ha0ye** [comment]
now also addressing #218

**Comment by fmichonneau** [comment]
Thanks @ha0ye for your first contribution to Data Carpentry's R lesson!

These are really useful edits. I'm going to merge this PR, but I'm going to keep the R lower case in the file name of lesson 5. I think it's better to be consistent in using lower case everywhere, even if seeing a lower case r makes me cringe a little :grimacing:

**Comment by ha0ye** [comment]
@fmichonneau, should the filenames for lesson 01 be lowercase then? It's currently "01-intro-to-R"...

**Comment by fmichonneau** [comment]
Good catch! I'm going to rename it. Thanks for pointing this out

**Pull request merged**
