### PR TITLE
helping to remember + talk about c() with "chain"?

### PR DESCRIPTION
**Pull request by steltenpower**
As concatenate is rather long ... and to many people means adding strings together in a way that can't be undone

### CODE REVIEW

**Comment by steltenpower** [comment]
Have a better idea?

**Comment by fmichonneau** [comment]
could any other @datacarpentry/r-ecology-lesson-maintainers confirm they are OK with this change?

**Comment by mondorescue** [comment]
@fmichonneau I would stay close to the documentation of `c()`, so if "concatenate" is too long, then use "combine" instead. "Chain" is something new. I would reject this PR.

**Comment by steltenpower** [comment]
I'm all for staying with terminology used elsewhere and all for consistency within a carpentry lesson. But my limited me hasn't seen the one super-clear and consistent thing to stick to.
Why I chose "chain": you can still see the individual parts that went into it; a metal chain consisting of links. Without keeping extra administration you can reverse the operation, which is not the case for a string concatenation.

**Comment by Teebusch** [comment]
Concatenate means ["to link together in a series or chain"](https://www.merriam-webster.com/dictionary/concatenate), so semantically it isn't very different from "chain".

Anyways, the documentation for `c()` says "This is a generic function which **combines** its arguments." so I would agree with @mondorescue - stick with the official docs and call it "combine".

**Comment by mondorescue** [comment]
We will close this PR.  @steltenpower thank you for the suggestion.

**Pull request closed without merging**
