### PR TITLE
Ignore non-Travis edits to rmarkdown::render_site() output

### PR DESCRIPTION
**Pull request by katrinleinweber**
As suggested in https://github.com/datacarpentry/R-ecology-lesson/pull/563#issuecomment-529850851

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Apologies for the multiple commits. My local git didn't fetch this patch-branch for some reason.

**Comment by katrinleinweber** [comment]
Does "[...] generated by Travis" also apply to [all `...-1.png` files in `img/`](https://github.com/datacarpentry/R-ecology-lesson/tree/2119e487b3284aab27cff51893cd604d1363bdfd/img)? If yes, we could delete them as well.

I currently observe lots of diffs in those image files when I `knit` manually.

**Comment by fmichonneau** [comment]
> Does "[...] generated by Travis" also apply to all ...-1.png files in img/? If yes, we could delete them as well.

Yes it does, I think they also all start with `R-ecology-`

**Comment by fmichonneau** [comment]
thank you for this contribution Katrin!

**Comment by katrinleinweber** [comment]
You're welcome & thanks for merging :-)

**Pull request merged**
